<?php

declare(strict_types=1);

namespace Greenlight\PhpStan;

use Greenlight\Attribute\CoverageIgnore;
use Greenlight\Expect\Expectation;

/**
 * Renders the IDE helper file that gives editors autocomplete for extension
 * matchers.
 *
 * The PHPStan extension checks matcher calls during analysis, but IDE
 * completion comes from indexers, which never execute PHPStan plugins. This
 * renders the established workaround: a file containing a duplicate
 * declaration of Expectation whose docblock lists every configured matcher
 * as an @method annotation. PhpStorm and Intelephense merge members from
 * duplicate class declarations, so the matchers complete with real
 * signatures.
 *
 * The generated file is never executed or autoloaded; it exists only to be
 * indexed. It should be gitignored and regenerated whenever matchers change.
 * Signatures come from the same MatcherMap the PHPStan extension reads, so
 * completion and analysis agree.
 *
 * @internal
 */
final readonly class IdeHelper
{
    #[CoverageIgnore]
    private function __construct() {}

    public static function render(MatcherMap $map): string
    {
        $annotations = [];

        foreach ($map->names() as $name) {
            $parameters = \array_map(
                static fn(\ReflectionParameter $parameter): string => MatcherMap::parameterSignature($parameter, 'null'),
                $map->parameters($name),
            );

            $annotations[] = \sprintf(' * @method self %s(%s)', $name, \implode(', ', $parameters));
        }

        $expectation = new \ReflectionClass(Expectation::class);

        return \sprintf(
            <<<'PHP'
                <?php

                /**
                 * Generated by "greenlight ide-helper" so IDEs autocomplete the extension
                 * matchers configured in greenlight.php. Never executed or autoloaded;
                 * gitignore it and regenerate after changing matchers.
                 */

                declare(strict_types=1);

                namespace %s;

                /**
                %s
                 */
                final class %s {}

                PHP,
            $expectation->getNamespaceName(),
            \implode("\n", $annotations),
            $expectation->getShortName(),
        );
    }
}
