<?php

declare(strict_types=1);

namespace Greenlight\PhpStan;

use Greenlight\Attribute\CoverageIgnore;
use Greenlight\Expect\Expectation;
use Greenlight\Expect\TemporalExpectation;

/**
 * IDE indexers do not run PHPStan plugins, so the helper duplicates the
 * Expectation declaration with configured matchers as @method annotations.
 *
 * The generated file is never executed or autoloaded; it exists only to be
 * indexed. Regenerate it when matchers change. Signatures share MatcherMap
 * with the PHPStan extension.
 *
 * @internal
 */
final readonly class IdeHelper
{
    #[CoverageIgnore]
    private function __construct() {}

    public static function render(MatcherMap $map): string
    {
        $annotations = [];

        foreach ($map->names() as $name) {
            $parameters = \array_map(
                static fn(\ReflectionParameter $parameter): string => MatcherMap::parameterSignature($parameter, 'null'),
                $map->parameters($name),
            );

            $annotations[] = \sprintf(' * @method self %s(%s)', $name, \implode(', ', $parameters));
        }

        $expectation = new \ReflectionClass(Expectation::class);
        $temporal = new \ReflectionClass(TemporalExpectation::class);

        return \sprintf(
            <<<'PHP'
                <?php

                /**
                 * Generated by "greenlight ide-helper" so IDEs autocomplete the extension
                 * matchers configured in greenlight.php. Never executed or autoloaded;
                 * gitignore it and regenerate after changing matchers.
                 */

                declare(strict_types=1);

                namespace %s;

                /**
                %s
                 */
                final class %s {}

                /**
                %s
                 */
                abstract class %s {}

                PHP,
            $expectation->getNamespaceName(),
            \implode("\n", $annotations),
            $expectation->getShortName(),
            \implode("\n", $annotations),
            $temporal->getShortName(),
        );
    }
}
