<?php

declare(strict_types=1);

namespace Greenlight\Doubles;

use Greenlight\Internal\Filesystem\AtomicFile;
use Greenlight\Internal\Filesystem\AtomicFileError;
use Greenlight\Internal\Php\ErrorTrap;

/**
 * Proxy class names contain a hash of their method signatures. Thus,
 * unchanged types reuse code from the cache. Parent constructors do not run.
 *
 * The generator does not support final classes, readonly classes, enums,
 * partial mocks, or static interception. It cannot intercept a final method
 * on a supported class. Such a method keeps its actual implementation. The
 * implementation uses an object whose constructor did not run. Prefer an
 * interface as the type for a double.
 *
 * @internal
 */
final readonly class ProxyGenerator
{
    private const string PROXY_NAMESPACE = 'Greenlight\Doubles\Generated';

    private const string HANDLER_PROPERTY = '__greenlightHandler';

    /**
     * @param non-empty-string $directory
     */
    public function __construct(private string $directory) {}

    /**
     * @param class-string $type
     *
     * @return class-string
     * @throws InvalidDoubleUsage
     */
    public function proxyClass(string $type): string
    {
        /** @var array<string, class-string> $classes */
        static $classes = [];
        $key = \strtolower($type);

        if (isset($classes[$key])) {
            return $classes[$key];
        }

        $reflection = $this->reflectDoubleable($type);

        $body = $this->renderBody($reflection);
        $hash = \substr(\sha1($reflection->name . "\n" . $body), 0, 12);
        $shortName = \preg_replace('/[^A-Za-z0-9_]/', '_', $reflection->getShortName()) . '_' . $hash;
        $proxyClass = self::PROXY_NAMESPACE . '\\' . $shortName;

        if (!\class_exists($proxyClass, false)) {
            $file = $this->directory . '/' . $shortName . '.php';
            $fileExists = ErrorTrap::run(static fn() => \is_file($file));

            if (!$fileExists) {
                $this->write($file, $this->renderFile($reflection, $shortName, $body));
            }

            ErrorTrap::run(
                static function () use ($file) {
                    require $file;
                },
                wrap: static fn(\Throwable $failure): InvalidDoubleUsage =>
                    InvalidDoubleUsage::proxyFileNotLoaded($file, $failure),
            );

            if (!\class_exists($proxyClass, false)) {
                throw InvalidDoubleUsage::proxyFileNotLoaded($file);
            }
        }

        return $classes[$key] = $proxyClass;
    }

    /**
     * @param class-string $type
     *
     * @return \ReflectionClass<object>
     * @throws InvalidDoubleUsage
     */
    private function reflectDoubleable(string $type): \ReflectionClass
    {
        if (\interface_exists($type)) {
            return new \ReflectionClass($type);
        }

        if (\enum_exists($type)) {
            throw InvalidDoubleUsage::cannotDoubleEnum($type);
        }

        if (\class_exists($type)) {
            $reflection = new \ReflectionClass($type);

            if ($reflection->isReadOnly()) {
                throw InvalidDoubleUsage::cannotDoubleReadonly($type);
            }

            if ($reflection->isFinal()) {
                throw InvalidDoubleUsage::cannotDoubleFinal($type);
            }

            return $reflection;
        }

        if (\trait_exists($type)) {
            throw InvalidDoubleUsage::cannotDoubleTrait($type);
        }

        throw InvalidDoubleUsage::notDoubleable($type);
    }

    /**
     * @param \ReflectionClass<object> $reflection
     */
    private function renderFile(\ReflectionClass $reflection, string $shortName, string $body): string
    {
        $relation = $reflection->isInterface()
            ? \sprintf('implements \%s, \Greenlight\Doubles\GeneratedProxy', $reflection->name)
            : \sprintf('extends \%s implements \Greenlight\Doubles\GeneratedProxy', $reflection->name);

        return "<?php\n\n"
            . "declare(strict_types=1);\n\n"
            . 'namespace ' . self::PROXY_NAMESPACE . ";\n\n"
            . \sprintf("// Generated by Greenlight for %s. Do not edit. You can safely delete this file.\n", $reflection->name)
            . \sprintf("final class %s %s\n{\n%s}\n", $shortName, $relation, $body);
    }

    /**
     * @param \ReflectionClass<object> $reflection
     * @throws InvalidDoubleUsage
     */
    private function renderBody(\ReflectionClass $reflection): string
    {
        if ($reflection->hasProperty(self::HANDLER_PROPERTY)) {
            $property = $reflection->getProperty(self::HANDLER_PROPERTY);

            if (!$property->isPrivate()) {
                throw InvalidDoubleUsage::handlerPropertyCollision($property->getDeclaringClass()->name);
            }
        }

        $sections = [
            \sprintf("    private \\Greenlight\\Doubles\\CallHandler \$%s;\n", self::HANDLER_PROPERTY),
            \sprintf(
                "    public function __greenlightAttachHandler(\\Greenlight\\Doubles\\CallHandler \$handler): void\n"
                . "    {\n        \$this->%s = \$handler;\n    }\n",
                self::HANDLER_PROPERTY,
            ),
        ];

        foreach ($this->doubledProperties($reflection) as $property) {
            $sections[] = $this->renderProperty($property);
        }

        foreach ($reflection->getMethods() as $method) {
            $rendered = $this->renderMethod($method);

            if ($rendered !== null) {
                $sections[] = $rendered;
            }
        }

        if (!$reflection->isInterface() && $reflection->hasMethod('__destruct') && !$reflection->getMethod('__destruct')->isFinal()) {
            $sections[] = "    public function __destruct() {}\n";
        }

        return \implode("\n", $sections);
    }

    /**
     * The proxy class must declare interface properties and abstract hooked
     * properties. A plain property satisfies both get and set requirements.
     *
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<\ReflectionProperty>
     */
    private function doubledProperties(\ReflectionClass $reflection): array
    {
        return \array_values(\array_filter(
            $reflection->getProperties(),
            static fn(\ReflectionProperty $property): bool => $reflection->isInterface() || $property->isAbstract(),
        ));
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function renderProperty(\ReflectionProperty $property): string
    {
        $visibility = $property->isProtected() ? 'protected' : 'public';
        $type = $property->getType();
        $rendered = $type === null ? '' : TypeRenderer::render($type, $property->getDeclaringClass()) . ' ';

        return \sprintf("    %s %s\$%s;\n", $visibility, $rendered, $property->name);
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function renderMethod(\ReflectionMethod $method): ?string
    {
        $name = \strtolower($method->name);

        if (\in_array($name, ['__construct', '__destruct'], true)) {
            return null;
        }

        if ($method->isPrivate()) {
            return null;
        }

        if ($name === '__greenlightattachhandler') {
            throw InvalidDoubleUsage::attachHandlerCollision($method->getDeclaringClass()->name);
        }

        if ($method->isFinal()
            || ($method->isProtected() && !$method->isAbstract())
        ) {
            return null;
        }

        if ($method->isStatic()) {
            return $method->isAbstract() ? $this->renderStaticStub($method) : null;
        }

        return $this->renderInstanceMethod($method);
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function renderInstanceMethod(\ReflectionMethod $method): string
    {
        $returnType = $method->getReturnType() ?? $method->getTentativeReturnType();
        $returnName = $returnType instanceof \ReflectionNamedType ? $returnType->getName() : null;
        $arguments = $this->renderInvocationArguments($method);

        $invoke = \sprintf(
            "\$this->%s->invoke(\$this, '%s', %s);",
            self::HANDLER_PROPERTY,
            $method->name,
            $arguments,
        );

        if ($returnName === 'void') {
            $body = '        ' . $invoke . "\n";
        } elseif ($returnName === 'never') {
            $body = '        ' . $invoke . "\n"
                . \sprintf(
                    "        throw \\Greenlight\\Doubles\\InvalidDoubleUsage::neverMethodRequiresThrow('%s', '%s');\n",
                    $method->getDeclaringClass()->name,
                    $method->name,
                );
        } else {
            $body = '        $__greenlightResult = ' . $invoke . "\n"
                . "        return \$__greenlightResult;\n";
        }

        return \sprintf(
            "    %s\n    {\n%s    }\n",
            $this->renderSignature($method, $returnType),
            $body,
        );
    }

    private function renderInvocationArguments(\ReflectionMethod $method): string
    {
        $parameters = $method->getParameters();

        if (!\array_any($parameters, static fn(\ReflectionParameter $parameter): bool => $parameter->isPassedByReference())) {
            return '\func_get_args()';
        }

        $arguments = \array_map(
            static function (\ReflectionParameter $parameter): string {
                $prefix = $parameter->isVariadic()
                    ? '...'
                    : ($parameter->isPassedByReference() ? '&' : '');

                return $prefix . '$' . $parameter->name;
            },
            $parameters,
        );

        return \sprintf(
            '\array_slice([%s], 0, \func_num_args())',
            \implode(', ', $arguments),
        );
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function renderStaticStub(\ReflectionMethod $method): string
    {
        $body = \sprintf(
            "        throw \\Greenlight\\Doubles\\InvalidDoubleUsage::staticMethod('%s', '%s');\n",
            $method->getDeclaringClass()->name,
            $method->name,
        );

        return \sprintf(
            "    %s\n    {\n%s    }\n",
            $this->renderSignature($method, $method->getReturnType() ?? $method->getTentativeReturnType(), static: true),
            $body,
        );
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function renderSignature(\ReflectionMethod $method, ?\ReflectionType $returnType, bool $static = false): string
    {
        $context = $method->getDeclaringClass();

        $parameters = \implode(', ', \array_map(
            fn(\ReflectionParameter $parameter): string => $this->renderParameter($parameter, $context),
            $method->getParameters(),
        ));

        return \sprintf(
            '%s %sfunction %s%s(%s)%s',
            $method->isProtected() ? 'protected' : 'public',
            $static ? 'static ' : '',
            $method->returnsReference() ? '&' : '',
            $method->name,
            $parameters,
            $returnType instanceof \ReflectionType ? ': ' . TypeRenderer::render($returnType, $context) : '',
        );
    }

    /**
     * @param \ReflectionClass<object> $context
     * @throws InvalidDoubleUsage
     */
    private function renderParameter(\ReflectionParameter $parameter, \ReflectionClass $context): string
    {
        $type = $parameter->getType();
        $source = $type === null ? '' : TypeRenderer::render($type, $context) . ' ';

        if ($parameter->isPassedByReference()) {
            $source .= '&';
        }

        if ($parameter->isVariadic()) {
            $source .= '...';
        }

        $source .= '$' . $parameter->name;

        if (!$parameter->isVariadic() && $parameter->isOptional()) {
            $source .= ' = ' . $this->renderDefault($parameter, $context);
        }

        return $source;
    }

    /**
     * @param \ReflectionClass<object> $context
     * @throws InvalidDoubleUsage
     */
    private function renderDefault(\ReflectionParameter $parameter, \ReflectionClass $context): string
    {
        if (!$parameter->isDefaultValueAvailable()) {
            throw InvalidDoubleUsage::defaultValueNotReproducible($parameter->name, $context->name, $parameter->getDeclaringFunction()->name);
        }

        if ($parameter->isDefaultValueConstant()) {
            $constant = $parameter->getDefaultValueConstantName();

            if ($constant === null) {
                throw InvalidDoubleUsage::defaultConstantUnresolvable($parameter->name);
            }

            if (\str_starts_with($constant, 'self::')) {
                $constant = $context->name . '::' . \substr($constant, 6);
            }

            if (\str_starts_with($constant, 'parent::')) {
                $parent = $context->getParentClass();

                if ($parent === false) {
                    throw InvalidDoubleUsage::parentTypeWithoutParent($context->name);
                }

                $constant = $parent->name . '::' . \substr($constant, 8);
            }

            $separator = \strrpos($constant, '::');

            if ($separator !== false) {
                $owner = \substr($constant, 0, $separator);

                if (\class_exists($owner)) {
                    $member = new \ReflectionClass($owner)->getReflectionConstant(\substr($constant, $separator + 2));

                    if ($member instanceof \ReflectionClassConstant && $member->isPrivate()) {
                        // A child proxy cannot access the parent's private constant.
                        $value = $parameter->getDefaultValue();

                        if (ParameterDefaultExpression::containsObject($value)) {
                            throw InvalidDoubleUsage::objectDefaultScopeUnavailable($parameter->name, $context->name, $parameter->getDeclaringFunction()->name);
                        }

                        return \var_export($value, true);
                    }
                }
            }

            return '\\' . $constant;
        }

        $expression = ParameterDefaultExpression::render($parameter, $context);

        if ($expression !== null) {
            return $expression;
        }

        $value = $parameter->getDefaultValue();

        if (ParameterDefaultExpression::containsObject($value)) {
            return ParameterDefaultExpression::render($parameter, $context, requireSource: true)
                ?? throw InvalidDoubleUsage::objectDefaultNotReproducible($parameter->name, $context->name, $parameter->getDeclaringFunction()->name);
        }

        return \var_export($value, true);
    }

    /**
     * @throws InvalidDoubleUsage
     */
    private function write(string $file, string $source): void
    {
        $directory = $this->directory;

        $directoryExists = ErrorTrap::run(static fn() => \is_dir($directory));

        if (!$directoryExists && !ErrorTrap::run(static fn() => \mkdir($directory, 0o777, true), $warning)) {
            $directoryExists = ErrorTrap::run(static fn() => \is_dir($directory));

            if (!$directoryExists) {
                throw InvalidDoubleUsage::proxyDirectoryNotCreated($directory, $warning);
            }
        }

        try {
            AtomicFile::write($file, $source);
        } catch (AtomicFileError $error) {
            throw InvalidDoubleUsage::proxyFileNotWritten($file, $error);
        }
    }
}
