<?php

declare(strict_types=1);

namespace Greenlight\Doubles;

/**
 * Generates, caches, and loads proxy classes for doubled types. Interfaces
 * get generated implementations; non-final classes get generated subclasses
 * whose parent constructor never runs. Every overridable instance method
 * delegates to the attached CallHandler.
 *
 * Generated code is written under the configured directory (by default a
 * per-project directory under the system temp dir) so it is opcache friendly
 * and debuggable. The class name embeds a hash of the doubled type's method
 * signatures, so a signature change generates a new class and file while
 * unchanged types reuse the cached one, within a process and across runs.
 *
 * Boundaries, by design: no final classes, no readonly classes, no enums, no
 * partial mocks, no static method interception. Final methods on otherwise
 * doubleable classes are not intercepted and keep their real implementation,
 * which runs against an object whose constructor never ran; prefer doubling
 * an interface.
 *
 * @internal
 */
final readonly class ProxyGenerator
{
    private const string PROXY_NAMESPACE = 'Greenlight\Doubles\Generated';

    private const string HANDLER_PROPERTY = '__greenlightHandler';

    /**
     * @param non-empty-string $directory
     */
    public function __construct(
        private string $directory,
    ) {}

    /**
     * @param class-string $type
     *
     * @return class-string
     */
    public function proxyClass(string $type): string
    {
        $reflection = $this->reflectDoubleable($type);

        $body = $this->renderBody($reflection);
        $hash = \substr(\sha1($reflection->name . "\n" . $body), 0, 12);
        $shortName = \preg_replace('/[^A-Za-z0-9_]/', '_', $reflection->getShortName()) . '_' . $hash;
        $proxyClass = self::PROXY_NAMESPACE . '\\' . $shortName;

        if (!\class_exists($proxyClass, false)) {
            $file = $this->directory . '/' . $shortName . '.php';

            if (!\is_file($file)) {
                $this->write($file, $this->renderFile($reflection, $shortName, $body));
            }

            require $file;
        }

        \assert(\class_exists($proxyClass, false));

        return $proxyClass;
    }

    /**
     * @param class-string $type
     *
     * @return \ReflectionClass<object>
     */
    private function reflectDoubleable(string $type): \ReflectionClass
    {
        if (\interface_exists($type)) {
            return new \ReflectionClass($type);
        }

        if (\enum_exists($type)) {
            throw new DoublesError(\sprintf('%s is an enum and cannot be doubled. Double an interface it implements instead.', $type));
        }

        if (\class_exists($type)) {
            $reflection = new \ReflectionClass($type);

            if ($reflection->isReadOnly()) {
                throw new DoublesError(\sprintf('%s is a readonly class and cannot be doubled in v1. Double an interface instead.', $type));
            }

            if ($reflection->isFinal()) {
                throw new DoublesError(\sprintf('%s is final and cannot be doubled. Double an interface instead; that boundary is deliberate.', $type));
            }

            return $reflection;
        }

        if (\trait_exists($type)) {
            throw new DoublesError(\sprintf('%s is a trait and cannot be doubled. Double a class or interface using it instead.', $type));
        }

        throw new DoublesError(\sprintf('%s is not a loadable class or interface, so it cannot be doubled.', $type));
    }

    /**
     * @param \ReflectionClass<object> $reflection
     */
    private function renderFile(\ReflectionClass $reflection, string $shortName, string $body): string
    {
        $relation = $reflection->isInterface()
            ? \sprintf('implements \%s, \Greenlight\Doubles\GeneratedProxy', $reflection->name)
            : \sprintf('extends \%s implements \Greenlight\Doubles\GeneratedProxy', $reflection->name);

        return "<?php\n\n"
            . "declare(strict_types=1);\n\n"
            . 'namespace ' . self::PROXY_NAMESPACE . ";\n\n"
            . \sprintf("// Generated by Greenlight for %s. Do not edit; safe to delete.\n", $reflection->name)
            . \sprintf("final class %s %s\n{\n%s}\n", $shortName, $relation, $body);
    }

    /**
     * @param \ReflectionClass<object> $reflection
     */
    private function renderBody(\ReflectionClass $reflection): string
    {
        $sections = [
            \sprintf("    private \\Greenlight\\Doubles\\CallHandler \$%s;\n", self::HANDLER_PROPERTY),
            \sprintf(
                "    public function __greenlightAttachHandler(\\Greenlight\\Doubles\\CallHandler \$handler): void\n"
                . "    {\n        \$this->%s = \$handler;\n    }\n",
                self::HANDLER_PROPERTY,
            ),
        ];

        foreach ($this->doubledProperties($reflection) as $property) {
            $sections[] = $this->renderProperty($property);
        }

        foreach ($reflection->getMethods() as $method) {
            $rendered = $this->renderMethod($method);

            if ($rendered !== null) {
                $sections[] = $rendered;
            }
        }

        if (!$reflection->isInterface() && $reflection->hasMethod('__destruct') && !$reflection->getMethod('__destruct')->isFinal()) {
            $sections[] = "    public function __destruct() {}\n";
        }

        return \implode("\n", $sections);
    }

    /**
     * Interface properties and abstract hooked properties must be declared
     * for the proxy to be instantiable; a plain property satisfies both get
     * and set requirements.
     *
     * @param \ReflectionClass<object> $reflection
     *
     * @return list<\ReflectionProperty>
     */
    private function doubledProperties(\ReflectionClass $reflection): array
    {
        return \array_values(\array_filter(
            $reflection->getProperties(),
            static fn(\ReflectionProperty $property): bool => $reflection->isInterface() || $property->isAbstract(),
        ));
    }

    private function renderProperty(\ReflectionProperty $property): string
    {
        $visibility = $property->isProtected() ? 'protected' : 'public';
        $type = $property->getType();
        $rendered = $type === null ? '' : TypeRenderer::render($type, $property->getDeclaringClass()) . ' ';

        return \sprintf("    %s %s\$%s;\n", $visibility, $rendered, $property->name);
    }

    private function renderMethod(\ReflectionMethod $method): ?string
    {
        if (\in_array($method->name, ['__construct', '__destruct', '__clone'], true)) {
            return null;
        }

        if ($method->name === '__greenlightAttachHandler') {
            throw new DoublesError(\sprintf('%s declares __greenlightAttachHandler(), which collides with the proxy plumbing.', $method->getDeclaringClass()->name));
        }

        if ($method->isFinal() || $method->isPrivate()) {
            return null;
        }

        if ($method->isStatic()) {
            return $method->isAbstract() ? $this->renderStaticStub($method) : null;
        }

        return $this->renderInstanceMethod($method);
    }

    private function renderInstanceMethod(\ReflectionMethod $method): string
    {
        $returnType = $method->getReturnType() ?? $method->getTentativeReturnType();
        $returnName = $returnType instanceof \ReflectionNamedType ? $returnType->getName() : null;

        $invoke = \sprintf(
            "\$this->%s->invoke(\$this, '%s', \\func_get_args());",
            self::HANDLER_PROPERTY,
            $method->name,
        );

        if ($returnName === 'void') {
            $body = '        ' . $invoke . "\n";
        } elseif ($returnName === 'never') {
            $body = '        ' . $invoke . "\n"
                . "        throw new \\Greenlight\\Doubles\\DoublesError('"
                . \sprintf('%s::%s() is declared never and must be configured with andThrows().', $method->getDeclaringClass()->name, $method->name)
                . "');\n";
        } else {
            $body = '        $__greenlightResult = ' . $invoke . "\n"
                . "        return \$__greenlightResult;\n";
        }

        return \sprintf(
            "    %s\n    {\n%s    }\n",
            $this->renderSignature($method, $returnType),
            $body,
        );
    }

    private function renderStaticStub(\ReflectionMethod $method): string
    {
        $body = \sprintf(
            "        throw new \\Greenlight\\Doubles\\DoublesError('Static method %s::%s() cannot be doubled; static interception is out of scope.');\n",
            $method->getDeclaringClass()->name,
            $method->name,
        );

        return \sprintf(
            "    %s\n    {\n%s    }\n",
            $this->renderSignature($method, $method->getReturnType() ?? $method->getTentativeReturnType(), static: true),
            $body,
        );
    }

    private function renderSignature(\ReflectionMethod $method, ?\ReflectionType $returnType, bool $static = false): string
    {
        $context = $method->getDeclaringClass();

        $parameters = \implode(', ', \array_map(
            fn(\ReflectionParameter $parameter): string => $this->renderParameter($parameter, $context),
            $method->getParameters(),
        ));

        return \sprintf(
            '%s %sfunction %s%s(%s)%s',
            $method->isProtected() ? 'protected' : 'public',
            $static ? 'static ' : '',
            $method->returnsReference() ? '&' : '',
            $method->name,
            $parameters,
            $returnType instanceof \ReflectionType ? ': ' . TypeRenderer::render($returnType, $context) : '',
        );
    }

    /**
     * @param \ReflectionClass<object> $context
     */
    private function renderParameter(\ReflectionParameter $parameter, \ReflectionClass $context): string
    {
        $type = $parameter->getType();
        $source = $type === null ? '' : TypeRenderer::render($type, $context) . ' ';

        if ($parameter->isPassedByReference()) {
            $source .= '&';
        }

        if ($parameter->isVariadic()) {
            $source .= '...';
        }

        $source .= '$' . $parameter->name;

        if (!$parameter->isVariadic() && $parameter->isOptional()) {
            $source .= ' = ' . $this->renderDefault($parameter, $context);
        }

        return $source;
    }

    /**
     * @param \ReflectionClass<object> $context
     */
    private function renderDefault(\ReflectionParameter $parameter, \ReflectionClass $context): string
    {
        if (!$parameter->isDefaultValueAvailable()) {
            throw new DoublesError(\sprintf(
                'The default value of parameter $%s of %s::%s() cannot be reproduced in a proxy.',
                $parameter->name,
                $context->name,
                $parameter->getDeclaringFunction()->name,
            ));
        }

        if ($parameter->isDefaultValueConstant()) {
            $constant = $parameter->getDefaultValueConstantName();

            if ($constant === null) {
                throw new DoublesError(\sprintf('The default constant of parameter $%s could not be resolved.', $parameter->name));
            }

            if (\str_starts_with($constant, 'self::')) {
                return '\\' . $context->name . '::' . \substr($constant, 6);
            }

            return '\\' . $constant;
        }

        $value = $parameter->getDefaultValue();

        if (\is_object($value) && !$value instanceof \UnitEnum) {
            throw new DoublesError(\sprintf(
                'The object default of parameter $%s of %s::%s() cannot be reproduced in a proxy. Double an interface without object defaults instead.',
                $parameter->name,
                $context->name,
                $parameter->getDeclaringFunction()->name,
            ));
        }

        return \var_export($value, true);
    }

    private function write(string $file, string $source): void
    {
        if (!\is_dir($this->directory) && !@\mkdir($this->directory, 0o777, true) && !\is_dir($this->directory)) {
            throw new DoublesError(\sprintf('The proxy directory %s could not be created.', $this->directory));
        }

        $temporary = $this->directory . '/.' . \bin2hex(\random_bytes(8)) . '.tmp';

        if (\file_put_contents($temporary, $source) === false || !\rename($temporary, $file)) {
            @\unlink($temporary);

            throw new DoublesError(\sprintf('The proxy file %s could not be written.', $file));
        }
    }
}
