<?php

declare(strict_types=1);

namespace Greenlight\Documentation\PhpExample;

/**
 * Extracts explicitly classified PHP fences from repository documentation.
 *
 * @internal
 */
final readonly class Extractor
{
    public function extract(string $root): Extraction
    {
        $snippets = [];
        $phpFences = 0;
        $displayFences = 0;
        $generatedDocuments = 0;
        $virtualFiles = [];
        $exampleTools = [];

        foreach ($this->markdownFiles($root) as $relativePath) {
            $contents = \file_get_contents($root . '/' . $relativePath);

            if ($contents === false) {
                throw DocumentationExampleError::sourceReadFailed($relativePath);
            }

            if (\str_contains(\substr($contents, 0, 512), 'This file is generated by ')) {
                ++$generatedDocuments;

                continue;
            }

            $lines = \preg_split('/\r\n|\n|\r/', $contents);

            if ($lines === false) {
                throw DocumentationExampleError::sourceSplitFailed($relativePath);
            }

            for ($index = 0, $lineCount = \count($lines); $index < $lineCount; ++$index) {
                if (\preg_match('/^ {0,3}(`{3,}|~{3,})([^\r\n]*)$/', $lines[$index], $opening) !== 1) {
                    continue;
                }

                $closingIndex = $this->closingFence($lines, $index, $opening[1]);

                if ($closingIndex === null) {
                    throw DocumentationExampleError::unclosedFence($relativePath, $index + 1);
                }

                $info = \trim($opening[2]);
                $languageToken = \strtok($info, " \t");
                $language = $languageToken === false ? '' : \strtolower($languageToken);

                if ($language !== 'php') {
                    $index = $closingIndex;

                    continue;
                }

                ++$phpFences;
                $metadataLine = $index > 0 ? $lines[$index - 1] : '';
                $metadata = $this->metadata($metadataLine, $relativePath, $index);

                if ($metadata === null) {
                    throw DocumentationExampleError::missingMetadata($relativePath, $index + 1);
                }

                $mode = $this->stringField($metadata, 'mode', $relativePath, $index);

                if ($mode === 'display') {
                    $this->stringField($metadata, 'reason', $relativePath, $index);
                    $this->rejectUnknownFields($metadata, ['mode', 'reason'], $relativePath, $index);
                    ++$displayFences;
                    $index = $closingIndex;

                    continue;
                }

                if (!\in_array($mode, ['file', 'statements', 'class-members'], true)) {
                    throw DocumentationExampleError::unsupportedMode($relativePath, $index, $mode);
                }

                $example = $this->stringField($metadata, 'example', $relativePath, $index);
                $virtualFile = $this->stringField($metadata, 'file', $relativePath, $index);
                $tools = $this->toolsField($metadata, $relativePath, $index);
                $this->rejectUnknownFields(
                    $metadata,
                    ['example', 'file', 'mode', 'tools'],
                    $relativePath,
                    $index,
                );
                $this->validateExample($example, $relativePath, $index);
                $this->validateVirtualFile($virtualFile, $relativePath, $index);

                $key = $example . '/' . $virtualFile;

                if (isset($virtualFiles[$key])) {
                    throw DocumentationExampleError::duplicateGeneratedFile($relativePath, $index, $key, $virtualFiles[$key]);
                }

                $toolKey = \implode(',', $tools);

                if (isset($exampleTools[$example]) && $exampleTools[$example] !== $toolKey) {
                    throw DocumentationExampleError::inconsistentTools($relativePath, $index, $example);
                }

                $virtualFiles[$key] = $relativePath . ':' . $index;
                $exampleTools[$example] = $toolKey;
                $bodyLines = \array_slice($lines, $index + 1, $closingIndex - $index - 1);

                $snippets[] = new Snippet(
                    sourcePath: $relativePath,
                    fenceLine: $index + 1,
                    sourceStartLine: $index + 2,
                    sourceEndLine: $closingIndex,
                    body: \implode("\n", $bodyLines) . "\n",
                    example: $example,
                    virtualFile: $virtualFile,
                    mode: $mode,
                    tools: $tools,
                );

                $index = $closingIndex;
            }
        }

        \usort(
            $snippets,
            static fn(Snippet $left, Snippet $right): int => [
                $left->example,
                $left->virtualFile,
            ] <=> [
                $right->example,
                $right->virtualFile,
            ],
        );

        return new Extraction(
            snippets: $snippets,
            phpFences: $phpFences,
            displayFences: $displayFences,
            generatedDocuments: $generatedDocuments,
        );
    }

    /**
     * @return list<string>
     */
    private function markdownFiles(string $root): array
    {
        $files = [];
        $readme = $root . '/README.md';

        if (\is_file($readme)) {
            $files[] = 'README.md';
        }

        $docs = $root . '/docs';

        if (\is_dir($docs)) {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($docs, \FilesystemIterator::SKIP_DOTS),
            );

            foreach ($iterator as $file) {
                if (!$file instanceof \SplFileInfo || !$file->isFile() || $file->getExtension() !== 'md') {
                    continue;
                }

                $files[] = \str_replace('\\', '/', \substr($file->getPathname(), \strlen($root) + 1));
            }
        }

        \sort($files, \SORT_STRING);

        return $files;
    }

    /**
     * @param list<string> $lines
     */
    private function closingFence(array $lines, int $openingIndex, string $opening): ?int
    {
        $marker = $opening[0];
        $markerLength = \strlen($opening);

        for ($candidate = $openingIndex + 1, $count = \count($lines); $candidate < $count; ++$candidate) {
            if (\preg_match('/^ {0,3}(`+|~+)\s*$/', $lines[$candidate], $closing) !== 1) {
                continue;
            }

            if ($closing[1][0] === $marker && \strlen($closing[1]) >= $markerLength) {
                return $candidate;
            }
        }

        return null;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function metadata(string $line, string $path, int $openingIndex): ?array
    {
        if (\preg_match('/^\s*<!-- php-example (\{.*\}) -->\s*$/', $line, $match) !== 1) {
            return null;
        }

        try {
            $metadata = \json_decode($match[1], true, flags: \JSON_THROW_ON_ERROR);
        } catch (\JsonException $error) {
            throw DocumentationExampleError::invalidMetadataJson($path, $openingIndex, $error);
        }

        if (!\is_array($metadata) || \array_is_list($metadata)) {
            throw DocumentationExampleError::metadataNotAnObject($path, $openingIndex);
        }

        $validated = [];

        foreach ($metadata as $field => $value) {
            if (!\is_string($field)) {
                throw DocumentationExampleError::invalidMetadataFieldName($path, $openingIndex);
            }

            $validated[$field] = $value;
        }

        return $validated;
    }

    /**
     * @param array<string, mixed> $metadata
     */
    private function stringField(array $metadata, string $field, string $path, int $openingIndex): string
    {
        $value = $metadata[$field] ?? null;

        if (!\is_string($value) || $value === '') {
            throw DocumentationExampleError::invalidMetadataString($path, $openingIndex, $field);
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $metadata
     *
     * @return list<'phpstan'|'rector'>
     */
    private function toolsField(array $metadata, string $path, int $openingIndex): array
    {
        $tools = $metadata['tools'] ?? null;

        if (!\is_array($tools) || !\array_is_list($tools)) {
            throw DocumentationExampleError::toolsNotAnArray($path, $openingIndex);
        }

        $validated = [];

        foreach ($tools as $tool) {
            if (!\is_string($tool) || !\in_array($tool, ['phpstan', 'rector'], true)) {
                throw DocumentationExampleError::unsupportedTool($path, $openingIndex);
            }

            if (!\in_array($tool, $validated, true)) {
                $validated[] = $tool;
            }
        }

        \sort($validated, \SORT_STRING);

        return $validated;
    }

    /**
     * @param array<string, mixed> $metadata
     * @param list<string>         $allowed
     */
    private function rejectUnknownFields(
        array $metadata,
        array $allowed,
        string $path,
        int $openingIndex,
    ): void {
        foreach (\array_keys($metadata) as $field) {
            if (!\in_array($field, $allowed, true)) {
                throw DocumentationExampleError::unsupportedMetadataField($path, $openingIndex, $field);
            }
        }
    }

    private function validateExample(string $example, string $path, int $openingIndex): void
    {
        if (\preg_match('/^[a-z0-9][a-z0-9._-]*$/', $example) !== 1) {
            throw DocumentationExampleError::invalidExampleName($path, $openingIndex, $example);
        }
    }

    private function validateVirtualFile(string $file, string $path, int $openingIndex): void
    {
        if (!\str_ends_with($file, '.php')
            || \str_starts_with($file, '/')
            || \str_contains($file, '\\')
            || \str_contains($file, "\0")
        ) {
            throw DocumentationExampleError::invalidExampleFile($path, $openingIndex, $file);
        }

        foreach (\explode('/', $file) as $segment) {
            if (\in_array($segment, ['', '.', '..'], true)) {
                throw DocumentationExampleError::invalidExamplePathSegment($path, $openingIndex, $file);
            }
        }
    }
}
